
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: "azure-vault-config"
spec:
  args:
    - --debug
  metadata:
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/role: "crossplane-providers"
      vault.hashicorp.com/agent-inject-secret-creds.txt: "generic/CloudProvider/bc9df749-9b5d-4bf5-88f4-3daced1cf31d"
      vault.hashicorp.com/agent-inject-template-creds.txt: |
        {{- with secret "generic/CloudProvider/bc9df749-9b5d-4bf5-88f4-3daced1cf31d" -}}
          [default]
          aws_access_key_id="{{ .access_key }}"
          aws_secret_access_key="{{ .secret_key }}"
        {{- end -}}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure
spec:
  package: ""
  controllerConfigRef:
    name: "azure-vault-config"
